name: Deploy Next.js App to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          token_format: "access_token"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        env:
          IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/alphamarket/nextjs-app:${{ github.sha }}
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
            -t $IMAGE .
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
          docker push $IMAGE

      - name: Deploy to Cloud Run
        env:
          IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/alphamarket/nextjs-app:${{ github.sha }}
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image $IMAGE \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars ^##^ALPHA_MARKET=${{ secrets.ALPHA_MARKET }},ALPHA_TOKEN=${{ secrets.ALPHA_TOKEN }},EXPONENTIAL_BONDING_CURVE=${{ secrets.EXPONENTIAL_BONDING_CURVE }},EXPONENTIAL_PROXY=${{ secrets.EXPONENTIAL_PROXY }},EXPONENTIAL_TOKEN=${{ secrets.EXPONENTIAL_TOKEN }},LINEAR_BONDING_CURVE=${{ secrets.LINEAR_BONDING_CURVE }},LINEAR_PROXY=${{ secrets.LINEAR_PROXY }},NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }},NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }},NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }},NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }},NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }},NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }},NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }},NEXT_PUBLIC_TWITTER_API_KEY=${{ secrets.NEXT_PUBLIC_TWITTER_API_KEY }},NEXT_PUBLIC_TWITTER_SECRET_KEY=${{ secrets.NEXT_PUBLIC_TWITTER_SECRET_KEY }},SEPOLIA_EXPONENTIAL_BONDING_CURVE=${{ secrets.SEPOLIA_EXPONENTIAL_BONDING_CURVE }},SEPOLIA_EXPONENTIAL_PROXY=${{ secrets.SEPOLIA_EXPONENTIAL_PROXY }},SEPOLIA_EXPONENTIAL_TOKEN=${{ secrets.SEPOLIA_EXPONENTIAL_TOKEN }},TIME_LOCK=${{ secrets.TIME_LOCK }}
