name: Deploy Next.js App to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      # Pre auth gcloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup Google Cloud SDK
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2 # Use the latest version
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          install_components: 'gcloud' # Explicitly install gcloud

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:${{ github.sha }} .

      # Push Docker image to Google Container Registry
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:${{ github.sha }}

      # Deploy to Cloud Run with environment variables
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:${{ github.sha }} \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars ALPHA_MARKET=${{ secrets.ALPHA_MARKET }} \
            --set-env-vars ALPHA_TOKEN=${{ secrets.ALPHA_TOKEN }} \
            --set-env-vars EXPONENTIAL_BONDING_CURVE=${{ secrets.EXPONENTIAL_BONDING_CURVE }} \
            --set-env-vars EXPONENTIAL_PROXY=${{ secrets.EXPONENTIAL_PROXY }} \
            --set-env-vars EXPONENTIAL_TOKEN=${{ secrets.EXPONENTIAL_TOKEN }} \
            --set-env-vars LINEAR_BONDING_CURVE=${{ secrets.LINEAR_BONDING_CURVE }} \
            --set-env-vars LINEAR_PROXY=${{ secrets.LINEAR_PROXY }} \
            --set-env-vars NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} \
            --set-env-vars NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }} \
            --set-env-vars NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} \
            --set-env-vars NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }} \
            --set-env-vars NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }} \
            --set-env-vars NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} \
            --set-env-vars NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }} \
            --set-env-vars NEXT_PUBLIC_TWITTER_API_KEY=${{ secrets.NEXT_PUBLIC_TWITTER_API_KEY }} \
            --set-env-vars NEXT_PUBLIC_TWITTER_SECRET_KEY=${{ secrets.NEXT_PUBLIC_TWITTER_SECRET_KEY }} \
            --set-env-vars SEPOLIA_EXPONENTIAL_BONDING_CURVE=${{ secrets.SEPOLIA_EXPONENTIAL_BONDING_CURVE }} \
            --set-env-vars SEPOLIA_EXPONENTIAL_PROXY=${{ secrets.SEPOLIA_EXPONENTIAL_PROXY }} \
            --set-env-vars SEPOLIA_EXPONENTIAL_TOKEN=${{ secrets.SEPOLIA_EXPONENTIAL_TOKEN }} \
            --set-env-vars TIME_LOCK=${{ secrets.TIME_LOCK }}
